name: Build cve report

on:
  schedule:
    # One daily refresh should be enough
    - cron: '10 3 * * *'
  workflow_dispatch:

jobs:
  build-cve-report:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install needed dependencies
        run: sudo snap install review-tools
      - name: Build the report
        id: build-the-report
        run: |
          ./snapscve.py -v -n
          if ! git diff --exit-code; then
            echo "::set-output name=changes::true"
          fi
      - name: Update the vcs
        if: steps.build-the-report.outputs.changes
        run: |
          git add cve.yml
          git config user.name "Update Bot"
          git config user.email "actions@github.com"
          git commit -m "Refresh the report"
          git push
